// AUTH
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH = 'CLEAR_AUTH';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';

// PROTECTED DATA
export const FETCH_PROTECTED_DATA_SUCCESS = 'FETCH_PROTECTED_DATA_SUCCESS';
export const FETCH_PROTECTED_DATA_ERROR = 'FETCH_PROTECTED_DATA_ERROR';

// VIEWS
export const TOGGLE_VIEW = 'TOGGLE_VIEW';